### ISSUE TITLE
Ajout

### ISSUE THREAD

**Issue by LucasB25** [AzuriomCommunity/Plugin-Launcher#4]
![image](https://user-images.githubusercontent.com/50886682/192759538-4ade6b06-e704-462a-a424-3a8a06fae043.png)
La possibilité soit de désactiver Linux, Windows et MacOs ou de mettre un message qui dit que ce n'est pas disponible

**Comment by Oximov** [comment]
Je vais ajouter la possibilité de désactiver des boutons sera ajouté bientôt, et la possibilité d'ajouter des images ne le sera pas.

**Comment by LucasB25** [comment]
pour l'image j'en ai pas parler

**Comment by LucasB25** [comment]
nope

**Comment by Oxim0v** [comment]
Ajouté dans https://github.com/AzuriomCommunity/Plugin-Launcher/commit/ba7194ee5d95b667f33d06cf3b7bf17c687b5deb
