### ISSUE TITLE
404

### ISSUE THREAD

**Issue by LucasB25** [AzuriomCommunity/Plugin-Launcher#5]
De temps en temps de façon aléatoire la page du launcher ce met en error 404
![image](https://user-images.githubusercontent.com/50886682/197335865-b248d835-5be7-44db-ad03-387a7f1664f8.png)
ce n'est pas propre a mon thème

**Comment by Oxim0v** [comment]
Es ce que tu as essayé du supprimer le plugin et le re installer ?
Par ce que j'ai jamais eu ce bug
