### ISSUE TITLE
Issue sur la taille des éléments de sélection de version Launcher

### ISSUE THREAD

**Issue by MasqueOu** [AzuriomCommunity/Plugin-Launcher#7]
Hello !
Petit problème vis à vis de la taille des éléments.

![image](https://github.com/AzuriomCommunity/Plugin-Launcher/assets/78830383/ca835e68-1060-4fa9-9c3e-1e221d62ec5a)

Le Linux est plus haut que les deux autres. 

Merci à toi.

**Comment by Oxim0v** [comment]
Hey,
En effet j'avais pas vue ça, je vais faire une maj soon !

Merci :)

**Comment by Oxim0v** [comment]
https://github.com/AzuriomCommunity/Plugin-Launcher/commit/9f346b86c41b570450a14fbc3a7b83b90e04c3d5
