### ISSUE TITLE
center les elements quand il n'y a a que 1 ou 2.

### ISSUE THREAD

**Issue by FrozerYTB** [AzuriomCommunity/Plugin-Launcher#8]
![Capture d'écran 2023-11-12 215400](https://github.com/AzuriomCommunity/Plugin-Launcher/assets/131524378/a1d8f681-d814-4fd6-ad1e-4be15e78ac30)
ce serait bien de centrer les icones quand il y en a que 1 ou 2 sinon ca fait moche

**Comment by MrMicky-FR** [comment]
Et ca serait encore mieux de ne pas discriminer certains joueurs selon leur OS en les empêchant d’utiliser le launcher

**Comment by FrozerYTB** [comment]
c'est vrai
